export const ACTION_SCOPES = [
    "application",
    "window",
    "file",
    "folder",
    "workspace",
    "process",
    "settings",
    "control-panel",
    "task-manager",
    "system"
];
export const DESKTOP_ACTION_KINDS = [
    "launch-program",
    "focus-window",
    "open-file",
    "open-folder",
    "create-file",
    "create-folder",
    "rename-item",
    "move-item",
    "delete-file",
    "delete-folder",
    "open-settings",
    "open-startup-apps",
    "open-storage-settings",
    "open-control-panel",
    "open-add-remove-programs",
    "open-registry-editor",
    "open-task-manager",
    "inspect-process",
    "terminate-process",
    "close-app",
    "uninstall-app",
    "ui-click",
    "ui-type",
    "ui-hotkey",
    "start-service",
    "stop-service",
    "restart-service",
    "set-registry-value",
    "delete-registry-value"
];
export const DESKTOP_ACTION_TARGET_KINDS = [
    "path",
    "directory",
    "process-id",
    "process-name",
    "window-title",
    "ui-element",
    "service-name",
    "registry-key",
    "registry-value",
    "installed-app",
    "uri",
    "program",
    "command"
];
export const DESKTOP_ACTION_RISK_CLASSES = ["low", "medium", "high", "critical"];
export const WORKFLOW_FAMILIES = [
    "research-report",
    "computer-health-report",
    "browser-playback",
    "browser-interaction",
    "file-management",
    "application-management",
    "window-control",
    "system-navigation",
    "process-control",
    "app-uninstall",
    "service-control",
    "registry-control",
    "ui-automation",
    "maintenance-review",
    "general"
];
export const WORKFLOW_STEP_KINDS = [
    "collect-web",
    "collect-machine",
    "collect-file",
    "collect-screen",
    "browser-open",
    "browser-search",
    "browser-extract",
    "browser-play",
    "browser-interact",
    "desktop-action",
    "service-action",
    "registry-action",
    "ui-action",
    "write-markdown",
    "resolve-installed-app",
    "confirm-approval"
];
export const WORKFLOW_SAVE_LOCATIONS = ["desktop", "documents", "workspace", "none"];
export const GOVERNANCE_APPROVAL_QUEUE_STATUSES = [
    "pending",
    "approved",
    "consumed",
    "denied",
    "blocked",
    "revoked",
    "expired"
];
export const IPC_CHANNELS = {
    appHealth: "app:health",
    modelHealth: "model:health",
    listModels: "model:list",
    sendChat: "chat:send",
    chatStream: "chat:stream",
    reasoningTrace: "chat:reasoning-trace",
    backgroundSync: "chat:background-sync",
    createConversation: "conversation:create",
    listConversations: "conversation:list",
    loadConversation: "conversation:load",
    clearConversation: "conversation:clear",
    deleteConversation: "conversation:delete",
    searchMemories: "memory:search",
    listMemories: "memory:list",
    deleteMemory: "memory:delete",
    desktopActionCatalog: "desktop-actions:list",
    desktopActionSuggest: "desktop-actions:suggest",
    desktopActionApprove: "desktop-actions:approve",
    desktopActionExecute: "desktop-actions:execute",
    rollbackDesktopAction: "desktop-actions:rollback",
    workflowPlanSuggest: "workflow:plan",
    workflowApprove: "workflow:approve",
    workflowExecute: "workflow:execute",
    workflowProgress: "workflow:progress",
    governanceDashboard: "governance:dashboard",
    governanceApprovalQueue: "governance:approvals",
    governanceAuditQuery: "governance:audit-query",
    contextPreview: "context:preview",
    promptEvaluationRun: "prompt-eval:run",
    awarenessQuery: "awareness:query",
    officialKnowledgeSources: "knowledge:sources",
    officialKnowledgeSourceUpdate: "knowledge:source-update",
    officialKnowledgeSourceRefresh: "knowledge:source-refresh",
    screenStatus: "screen:status",
    screenForegroundWindow: "screen:foreground-window",
    screenUiTree: "screen:ui-tree",
    screenLastEvents: "screen:last-events",
    screenStartAssist: "screen:start-assist",
    screenStopAssist: "screen:stop-assist",
    agentRuntimeRun: "agent-runtime:run",
    agentRuntimeList: "agent-runtime:list",
    agentRuntimeInspect: "agent-runtime:inspect",
    agentRuntimeResume: "agent-runtime:resume",
    agentRuntimeCancel: "agent-runtime:cancel",
    agentRuntimeRecover: "agent-runtime:recover",
    agentRuntimeProgress: "agent-runtime:progress"
};
